// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: customer_identity_bank/customer_identity_bank.proto

package customer_identity_bank

import (
	onboarding_pagination "github.com/djoonta/kponboardingproto/onboarding_pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerIdentityBankInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Foreign key: bank_id
	BankId string `protobuf:"bytes,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	// Foreign key: customer_identity_id
	CustomerIdentityId string `protobuf:"bytes,3,opt,name=customer_identity_id,json=customerIdentityId,proto3" json:"customer_identity_id,omitempty"`
	// Account number
	AccountNumber string `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Path to the card book image
	CardBookImage string `protobuf:"bytes,5,opt,name=card_book_image,json=cardBookImage,proto3" json:"card_book_image,omitempty"`
	// Path to the e-statement image
	EstatementImage string `protobuf:"bytes,6,opt,name=estatement_image,json=estatementImage,proto3" json:"estatement_image,omitempty"`
	// Created timestamp
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *CustomerIdentityBankInfo) Reset() {
	*x = CustomerIdentityBankInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankInfo) ProtoMessage() {}

func (x *CustomerIdentityBankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankInfo.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankInfo) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerIdentityBankInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerIdentityBankInfo) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *CustomerIdentityBankInfo) GetCustomerIdentityId() string {
	if x != nil {
		return x.CustomerIdentityId
	}
	return ""
}

func (x *CustomerIdentityBankInfo) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CustomerIdentityBankInfo) GetCardBookImage() string {
	if x != nil {
		return x.CardBookImage
	}
	return ""
}

func (x *CustomerIdentityBankInfo) GetEstatementImage() string {
	if x != nil {
		return x.EstatementImage
	}
	return ""
}

func (x *CustomerIdentityBankInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CustomerIdentityBankCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Foreign key: bank_id
	BankId string `protobuf:"bytes,1,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	// Foreign key: customer_identity_id
	CustomerIdentityId string `protobuf:"bytes,2,opt,name=customer_identity_id,json=customerIdentityId,proto3" json:"customer_identity_id,omitempty"`
	// Account number
	AccountNumber string `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Path to the card book image
	CardBookImage string `protobuf:"bytes,4,opt,name=card_book_image,json=cardBookImage,proto3" json:"card_book_image,omitempty"`
	// Path to the e-statement image
	EstatementImage string `protobuf:"bytes,5,opt,name=estatement_image,json=estatementImage,proto3" json:"estatement_image,omitempty"`
}

func (x *CustomerIdentityBankCreateRequest) Reset() {
	*x = CustomerIdentityBankCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankCreateRequest) ProtoMessage() {}

func (x *CustomerIdentityBankCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankCreateRequest.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankCreateRequest) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerIdentityBankCreateRequest) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *CustomerIdentityBankCreateRequest) GetCustomerIdentityId() string {
	if x != nil {
		return x.CustomerIdentityId
	}
	return ""
}

func (x *CustomerIdentityBankCreateRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CustomerIdentityBankCreateRequest) GetCardBookImage() string {
	if x != nil {
		return x.CardBookImage
	}
	return ""
}

func (x *CustomerIdentityBankCreateRequest) GetEstatementImage() string {
	if x != nil {
		return x.EstatementImage
	}
	return ""
}

type CustomerIdentityBankCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CustomerIdentityBankCreateResponse) Reset() {
	*x = CustomerIdentityBankCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankCreateResponse) ProtoMessage() {}

func (x *CustomerIdentityBankCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankCreateResponse.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankCreateResponse) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerIdentityBankCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CustomerIdentityBankUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Foreign key: bank_id
	BankId string `protobuf:"bytes,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	// Foreign key: customer_identity_id
	CustomerIdentityId string `protobuf:"bytes,3,opt,name=customer_identity_id,json=customerIdentityId,proto3" json:"customer_identity_id,omitempty"`
	// Account number
	AccountNumber string `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Path to the card book image
	CardBookImage string `protobuf:"bytes,5,opt,name=card_book_image,json=cardBookImage,proto3" json:"card_book_image,omitempty"`
	// Path to the e-statement image
	EstatementImage string `protobuf:"bytes,6,opt,name=estatement_image,json=estatementImage,proto3" json:"estatement_image,omitempty"`
}

func (x *CustomerIdentityBankUpdateRequest) Reset() {
	*x = CustomerIdentityBankUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankUpdateRequest) ProtoMessage() {}

func (x *CustomerIdentityBankUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankUpdateRequest.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankUpdateRequest) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerIdentityBankUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerIdentityBankUpdateRequest) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *CustomerIdentityBankUpdateRequest) GetCustomerIdentityId() string {
	if x != nil {
		return x.CustomerIdentityId
	}
	return ""
}

func (x *CustomerIdentityBankUpdateRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CustomerIdentityBankUpdateRequest) GetCardBookImage() string {
	if x != nil {
		return x.CardBookImage
	}
	return ""
}

func (x *CustomerIdentityBankUpdateRequest) GetEstatementImage() string {
	if x != nil {
		return x.EstatementImage
	}
	return ""
}

type CustomerIdentityBankUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CustomerIdentityBankUpdateResponse) Reset() {
	*x = CustomerIdentityBankUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankUpdateResponse) ProtoMessage() {}

func (x *CustomerIdentityBankUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankUpdateResponse.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankUpdateResponse) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{4}
}

func (x *CustomerIdentityBankUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CustomerIdentityBankDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CustomerIdentityBankDeleteRequest) Reset() {
	*x = CustomerIdentityBankDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankDeleteRequest) ProtoMessage() {}

func (x *CustomerIdentityBankDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankDeleteRequest.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankDeleteRequest) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{5}
}

func (x *CustomerIdentityBankDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CustomerIdentityBankDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CustomerIdentityBankDeleteResponse) Reset() {
	*x = CustomerIdentityBankDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankDeleteResponse) ProtoMessage() {}

func (x *CustomerIdentityBankDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankDeleteResponse.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankDeleteResponse) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{6}
}

func (x *CustomerIdentityBankDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CustomerIdentityBankFindIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CustomerIdentityBankFindIDRequest) Reset() {
	*x = CustomerIdentityBankFindIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankFindIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankFindIDRequest) ProtoMessage() {}

func (x *CustomerIdentityBankFindIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankFindIDRequest.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankFindIDRequest) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{7}
}

func (x *CustomerIdentityBankFindIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CustomerIdentityBankFindIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerIdentityBankInfo *CustomerIdentityBankInfo `protobuf:"bytes,1,opt,name=customer_identity_bank_info,json=customerIdentityBankInfo,proto3" json:"customer_identity_bank_info,omitempty"`
}

func (x *CustomerIdentityBankFindIDResponse) Reset() {
	*x = CustomerIdentityBankFindIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankFindIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankFindIDResponse) ProtoMessage() {}

func (x *CustomerIdentityBankFindIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankFindIDResponse.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankFindIDResponse) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{8}
}

func (x *CustomerIdentityBankFindIDResponse) GetCustomerIdentityBankInfo() *CustomerIdentityBankInfo {
	if x != nil {
		return x.CustomerIdentityBankInfo
	}
	return nil
}

type CustomerIdentityBankFindAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CustomerIdentityBankFindAllRequest) Reset() {
	*x = CustomerIdentityBankFindAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankFindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankFindAllRequest) ProtoMessage() {}

func (x *CustomerIdentityBankFindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankFindAllRequest.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankFindAllRequest) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{9}
}

func (x *CustomerIdentityBankFindAllRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *CustomerIdentityBankFindAllRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type CustomerIdentityBankFindAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerIdentityBanks []*CustomerIdentityBankInfo                     `protobuf:"bytes,1,rep,name=customer_identity_banks,json=customerIdentityBanks,proto3" json:"customer_identity_banks,omitempty"`
	Pagination            *onboarding_pagination.OnboardingPaginationInfo `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *CustomerIdentityBankFindAllResponse) Reset() {
	*x = CustomerIdentityBankFindAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerIdentityBankFindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerIdentityBankFindAllResponse) ProtoMessage() {}

func (x *CustomerIdentityBankFindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_identity_bank_customer_identity_bank_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerIdentityBankFindAllResponse.ProtoReflect.Descriptor instead.
func (*CustomerIdentityBankFindAllResponse) Descriptor() ([]byte, []int) {
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP(), []int{10}
}

func (x *CustomerIdentityBankFindAllResponse) GetCustomerIdentityBanks() []*CustomerIdentityBankInfo {
	if x != nil {
		return x.CustomerIdentityBanks
	}
	return nil
}

func (x *CustomerIdentityBankFindAllResponse) GetPagination() *onboarding_pagination.OnboardingPaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_customer_identity_bank_customer_identity_bank_proto protoreflect.FileDescriptor

var file_customer_identity_bank_customer_identity_bank_proto_rawDesc = []byte{
	0x0a, 0x33, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6b, 0x70, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x31, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x02, 0x0a, 0x18,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x42, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x12, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xe8, 0x01, 0x0a,
	0x21, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x62, 0x6f, 0x6f,
	0x6b, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x61, 0x72, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x10,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x22, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xf8, 0x01, 0x0a, 0x21, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x26, 0x0a, 0x0f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x42, 0x6f,
	0x6f, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x22, 0x3e, 0x0a, 0x22, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x33, 0x0a, 0x21, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x22, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x21, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x46,
	0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a,
	0x22, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x42, 0x61, 0x6e, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x1b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x70, 0x6f, 0x6e, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x18, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x4e, 0x0a, 0x22, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0xd7, 0x01, 0x0a, 0x23, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x17, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x61, 0x6e,
	0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x70, 0x6f, 0x6e, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x73, 0x12, 0x4b, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x6b, 0x70, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x6f, 0x6f, 0x6e, 0x74, 0x61, 0x2f,
	0x6b, 0x70, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_customer_identity_bank_customer_identity_bank_proto_rawDescOnce sync.Once
	file_customer_identity_bank_customer_identity_bank_proto_rawDescData = file_customer_identity_bank_customer_identity_bank_proto_rawDesc
)

func file_customer_identity_bank_customer_identity_bank_proto_rawDescGZIP() []byte {
	file_customer_identity_bank_customer_identity_bank_proto_rawDescOnce.Do(func() {
		file_customer_identity_bank_customer_identity_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_customer_identity_bank_customer_identity_bank_proto_rawDescData)
	})
	return file_customer_identity_bank_customer_identity_bank_proto_rawDescData
}

var file_customer_identity_bank_customer_identity_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_customer_identity_bank_customer_identity_bank_proto_goTypes = []interface{}{
	(*CustomerIdentityBankInfo)(nil),                       // 0: kponboardingproto.CustomerIdentityBankInfo
	(*CustomerIdentityBankCreateRequest)(nil),              // 1: kponboardingproto.CustomerIdentityBankCreateRequest
	(*CustomerIdentityBankCreateResponse)(nil),             // 2: kponboardingproto.CustomerIdentityBankCreateResponse
	(*CustomerIdentityBankUpdateRequest)(nil),              // 3: kponboardingproto.CustomerIdentityBankUpdateRequest
	(*CustomerIdentityBankUpdateResponse)(nil),             // 4: kponboardingproto.CustomerIdentityBankUpdateResponse
	(*CustomerIdentityBankDeleteRequest)(nil),              // 5: kponboardingproto.CustomerIdentityBankDeleteRequest
	(*CustomerIdentityBankDeleteResponse)(nil),             // 6: kponboardingproto.CustomerIdentityBankDeleteResponse
	(*CustomerIdentityBankFindIDRequest)(nil),              // 7: kponboardingproto.CustomerIdentityBankFindIDRequest
	(*CustomerIdentityBankFindIDResponse)(nil),             // 8: kponboardingproto.CustomerIdentityBankFindIDResponse
	(*CustomerIdentityBankFindAllRequest)(nil),             // 9: kponboardingproto.CustomerIdentityBankFindAllRequest
	(*CustomerIdentityBankFindAllResponse)(nil),            // 10: kponboardingproto.CustomerIdentityBankFindAllResponse
	(*onboarding_pagination.OnboardingPaginationInfo)(nil), // 11: kponboardingproto.OnboardingPaginationInfo
}
var file_customer_identity_bank_customer_identity_bank_proto_depIdxs = []int32{
	0,  // 0: kponboardingproto.CustomerIdentityBankFindIDResponse.customer_identity_bank_info:type_name -> kponboardingproto.CustomerIdentityBankInfo
	0,  // 1: kponboardingproto.CustomerIdentityBankFindAllResponse.customer_identity_banks:type_name -> kponboardingproto.CustomerIdentityBankInfo
	11, // 2: kponboardingproto.CustomerIdentityBankFindAllResponse.pagination:type_name -> kponboardingproto.OnboardingPaginationInfo
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_customer_identity_bank_customer_identity_bank_proto_init() }
func file_customer_identity_bank_customer_identity_bank_proto_init() {
	if File_customer_identity_bank_customer_identity_bank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankFindIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankFindIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankFindAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customer_identity_bank_customer_identity_bank_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerIdentityBankFindAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_customer_identity_bank_customer_identity_bank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customer_identity_bank_customer_identity_bank_proto_goTypes,
		DependencyIndexes: file_customer_identity_bank_customer_identity_bank_proto_depIdxs,
		MessageInfos:      file_customer_identity_bank_customer_identity_bank_proto_msgTypes,
	}.Build()
	File_customer_identity_bank_customer_identity_bank_proto = out.File
	file_customer_identity_bank_customer_identity_bank_proto_rawDesc = nil
	file_customer_identity_bank_customer_identity_bank_proto_goTypes = nil
	file_customer_identity_bank_customer_identity_bank_proto_depIdxs = nil
}
