// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: installment_category/installment_category.proto

package installment_category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallmentCategoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *InstallmentCategoryInfo) Reset() {
	*x = InstallmentCategoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_category_installment_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentCategoryInfo) ProtoMessage() {}

func (x *InstallmentCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_installment_category_installment_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentCategoryInfo.ProtoReflect.Descriptor instead.
func (*InstallmentCategoryInfo) Descriptor() ([]byte, []int) {
	return file_installment_category_installment_category_proto_rawDescGZIP(), []int{0}
}

func (x *InstallmentCategoryInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstallmentCategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallmentCategoryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InstallmentCategoryInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *InstallmentCategoryInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type InstallmentCategoryCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *InstallmentCategoryCreateRequest) Reset() {
	*x = InstallmentCategoryCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_category_installment_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentCategoryCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentCategoryCreateRequest) ProtoMessage() {}

func (x *InstallmentCategoryCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installment_category_installment_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentCategoryCreateRequest.ProtoReflect.Descriptor instead.
func (*InstallmentCategoryCreateRequest) Descriptor() ([]byte, []int) {
	return file_installment_category_installment_category_proto_rawDescGZIP(), []int{1}
}

func (x *InstallmentCategoryCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallmentCategoryCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type InstallmentCategoryCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *InstallmentCategoryCreateResponse) Reset() {
	*x = InstallmentCategoryCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_category_installment_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentCategoryCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentCategoryCreateResponse) ProtoMessage() {}

func (x *InstallmentCategoryCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installment_category_installment_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentCategoryCreateResponse.ProtoReflect.Descriptor instead.
func (*InstallmentCategoryCreateResponse) Descriptor() ([]byte, []int) {
	return file_installment_category_installment_category_proto_rawDescGZIP(), []int{2}
}

func (x *InstallmentCategoryCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InstallmentCategoryFindIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *InstallmentCategoryFindIDRequest) Reset() {
	*x = InstallmentCategoryFindIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_category_installment_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentCategoryFindIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentCategoryFindIDRequest) ProtoMessage() {}

func (x *InstallmentCategoryFindIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installment_category_installment_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentCategoryFindIDRequest.ProtoReflect.Descriptor instead.
func (*InstallmentCategoryFindIDRequest) Descriptor() ([]byte, []int) {
	return file_installment_category_installment_category_proto_rawDescGZIP(), []int{3}
}

func (x *InstallmentCategoryFindIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InstallmentCategoryFindIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstallmentCategory *InstallmentCategoryInfo `protobuf:"bytes,1,opt,name=installment_category,json=installmentCategory,proto3" json:"installment_category,omitempty"`
}

func (x *InstallmentCategoryFindIDResponse) Reset() {
	*x = InstallmentCategoryFindIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_category_installment_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentCategoryFindIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentCategoryFindIDResponse) ProtoMessage() {}

func (x *InstallmentCategoryFindIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installment_category_installment_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentCategoryFindIDResponse.ProtoReflect.Descriptor instead.
func (*InstallmentCategoryFindIDResponse) Descriptor() ([]byte, []int) {
	return file_installment_category_installment_category_proto_rawDescGZIP(), []int{4}
}

func (x *InstallmentCategoryFindIDResponse) GetInstallmentCategory() *InstallmentCategoryInfo {
	if x != nil {
		return x.InstallmentCategory
	}
	return nil
}

var File_installment_category_installment_category_proto protoreflect.FileDescriptor

var file_installment_category_installment_category_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x6b, 0x70, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x17, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x58, 0x0a, 0x20, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3d,
	0x0a, 0x21, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x32, 0x0a,
	0x20, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x82, 0x01, 0x0a, 0x21, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x14, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6b, 0x70, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x13, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x6f, 0x6f, 0x6e, 0x74, 0x61, 0x2f, 0x6b, 0x70, 0x6f,
	0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_installment_category_installment_category_proto_rawDescOnce sync.Once
	file_installment_category_installment_category_proto_rawDescData = file_installment_category_installment_category_proto_rawDesc
)

func file_installment_category_installment_category_proto_rawDescGZIP() []byte {
	file_installment_category_installment_category_proto_rawDescOnce.Do(func() {
		file_installment_category_installment_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_installment_category_installment_category_proto_rawDescData)
	})
	return file_installment_category_installment_category_proto_rawDescData
}

var file_installment_category_installment_category_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_installment_category_installment_category_proto_goTypes = []interface{}{
	(*InstallmentCategoryInfo)(nil),           // 0: kponboardingproto.InstallmentCategoryInfo
	(*InstallmentCategoryCreateRequest)(nil),  // 1: kponboardingproto.InstallmentCategoryCreateRequest
	(*InstallmentCategoryCreateResponse)(nil), // 2: kponboardingproto.InstallmentCategoryCreateResponse
	(*InstallmentCategoryFindIDRequest)(nil),  // 3: kponboardingproto.InstallmentCategoryFindIDRequest
	(*InstallmentCategoryFindIDResponse)(nil), // 4: kponboardingproto.InstallmentCategoryFindIDResponse
}
var file_installment_category_installment_category_proto_depIdxs = []int32{
	0, // 0: kponboardingproto.InstallmentCategoryFindIDResponse.installment_category:type_name -> kponboardingproto.InstallmentCategoryInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_installment_category_installment_category_proto_init() }
func file_installment_category_installment_category_proto_init() {
	if File_installment_category_installment_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_installment_category_installment_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentCategoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_category_installment_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentCategoryCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_category_installment_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentCategoryCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_category_installment_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentCategoryFindIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_category_installment_category_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentCategoryFindIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_installment_category_installment_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_installment_category_installment_category_proto_goTypes,
		DependencyIndexes: file_installment_category_installment_category_proto_depIdxs,
		MessageInfos:      file_installment_category_installment_category_proto_msgTypes,
	}.Build()
	File_installment_category_installment_category_proto = out.File
	file_installment_category_installment_category_proto_rawDesc = nil
	file_installment_category_installment_category_proto_goTypes = nil
	file_installment_category_installment_category_proto_depIdxs = nil
}
